"JAX_SEED": 0

"EXPLORATION_STEPS": 4e1 # 16e3
"TOTAL_STEPS": 8e2 # 1e6
"NUM_ENVS": 8 # 64
"BATCH_SIZE": 64 # 256

"ENV_NAME": "ant_4x2" 
"ENV_KWARGS": {}

#TD3 Parameters
"EXPLORATION_NOISE": 0.1 # Standard deviation of gaussian noise
"LR": 3e-4
"DISCOUNT": 0.99
"TAU": 0.005
"POLICY_NOISE": 0.2
"NOISE_CLIP": 0.5
"POLICY_FREQ": 2 # Frequency of Delayed policy updates

"NUM_CHECKPOINTS": 4